### ISSUE TITLE
Last published version of io.opentelemetry.semconv:opentelemetry-semconv

### ISSUE THREAD

**Issue by JnRouvignac** [open-telemetry/semantic-conventions-java#44]
Hello,

I am following what's described in [opentelemetry-java 1.31.0 release notes](https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.31.0):

> BREAKING: Stop publishing `io.opentelemetry:opentelemetry-semconv`. Please use `io.opentelemetry.semconv:opentelemetry-semconv:1.21.0-alpha` instead, which is published from [open-telemetry/semantic-conventions-java](https://github.com/open-telemetry/semantic-conventions-java). The new repository is published in lockstep with [open-telemetry/semantic-conventions](https://github.com/open-telemetry/semantic-conventions). (https://github.com/open-telemetry/opentelemetry-java/pull/5807)

When I look at the [releases of open-telemetry/semantic-conventions](https://github.com/open-telemetry/semantic-conventions/releases), the last release is `1.24.0`, and yet, when I go to [maven central](https://central.sonatype.com/artifact/io.opentelemetry.semconv/opentelemetry-semconv), the only release I can find is `1.23.1-alpha`. 

Since it is supposed to be "published in lockstep", I was expecting to find `1.24.0` in maven central.

Did I misunderstand something or is the publication mechanism broken?

Thanks

**Comment by jkwatson** [comment]
As I understand it, the "publication mechanism" is always triggered by a human, so it probably just hasn't been kicked off yet.

**Comment by jack-berg** [comment]
I'm blocking the 1.24.0 release on resolving #41 and #40. The process for releasing currently requires a very manual and error process process to retain any attributes that were removed from the semantic conventions with a `@Deprecated` annotation. We do this because of the open questions in #5, #6, and #22. 

However, #40 and #41 resolve these open questions with solutions that have been discussed and agreed on in various Java SIG meetings. Given that we have a path forward, and PRs in place to achieve it, we should take that route rather than continuing with the old process.

**Comment by JnRouvignac** [comment]
I see. Thanks for the explanation and good luck with automating the release process to get there. :muscle: 
Cheers

**Comment by JnRouvignac** [comment]
Thanks a lot for unblocking the release and doing a new one! We are about to consume it now. 🙂
